export const FONT_FACES = [
  // Anton Font Family
  {
    family: "Anton",
    path: "/fonts/Anton/Anton-Regular.ttf",
    weight: "normal",
    style: "normal",
  },
  // Bahnschrift Font Family
  {
    family: "Bahnschrift",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT.TTF",
    weight: "normal",
    style: "normal",
  },
  {
    family: "Bahnschrift Light",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 1.TTF",
    weight: "300",
    style: "normal",
  },
  {
    family: "Bahnschrift SemiLight",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 2.TTF",
    weight: "400",
    style: "normal",
  },
  {
    family: "Bahnschrift SemiBold",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 3.TTF",
    weight: "600",
    style: "normal",
  },
  {
    family: "Bahnschrift Bold",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 4.TTF",
    weight: "700",
    style: "normal",
  },
  {
    family: "Bahnschrift ExtraBold",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 5.TTF",
    weight: "800",
    style: "normal",
  },
  {
    family: "Bahnschrift Heavy",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 6.TTF",
    weight: "900",
    style: "normal",
  },
  {
    family: "Bahnschrift Black",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 7.TTF",
    weight: "900",
    style: "normal",
  },
  {
    family: "Bahnschrift Ultra",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 8.TTF",
    weight: "900",
    style: "normal",
  },
  {
    family: "Bahnschrift Thin",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 9.TTF",
    weight: "100",
    style: "normal",
  },
  {
    family: "Bahnschrift ExtraLight",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 10.TTF",
    weight: "200",
    style: "normal",
  },
  {
    family: "Bahnschrift Light Condensed",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 11.TTF",
    weight: "300",
    style: "normal",
  },
  {
    family: "Bahnschrift Condensed",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 12.TTF",
    weight: "400",
    style: "normal",
  },
  {
    family: "Bahnschrift Bold Condensed",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 13.TTF",
    weight: "700",
    style: "normal",
  },
  {
    family: "Bahnschrift ExtraBold Condensed",
    path: "/fonts/Bahnschrift-Font-Family/BAHNSCHRIFT 14.TTF",
    weight: "800",
    style: "normal",
  },

  // Evolventa Font Family
  {
    family: "Evolventa",
    path: "/fonts/evolventa-webfont/Evolventa-Regular.woff",
    weight: "normal",
    style: "normal",
  },
  {
    family: "Evolventa Oblique",
    path: "/fonts/evolventa-webfont/Evolventa-Oblique.woff",
    weight: "normal",
    style: "italic",
  },
  {
    family: "Evolventa Bold",
    path: "/fonts/evolventa-webfont/Evolventa-Bold.woff",
    weight: "700",
    style: "normal",
  },
  {
    family: "Evolventa Bold Oblique",
    path: "/fonts/evolventa-webfont/Evolventa-BoldOblique.woff",
    weight: "700",
    style: "italic",
  },

  // Georgia Pro Font Family
  {
    family: "Georgia Pro",
    path: "/fonts/georgia-pro/GeorgiaPro-Regular.ttf",
    weight: "normal",
    style: "normal",
  },
  {
    family: "Georgia Pro Italic",
    path: "/fonts/georgia-pro/GeorgiaPro-Italic.ttf",
    weight: "normal",
    style: "italic",
  },
  {
    family: "Georgia Pro Light",
    path: "/fonts/georgia-pro/GeorgiaPro-Light.ttf",
    weight: "300",
    style: "normal",
  },
  {
    family: "Georgia Pro Light Italic",
    path: "/fonts/georgia-pro/GeorgiaPro-LightItalic.ttf",
    weight: "300",
    style: "italic",
  },
  {
    family: "Georgia Pro Semibold",
    path: "/fonts/georgia-pro/GeorgiaPro-Semibold.ttf",
    weight: "600",
    style: "normal",
  },
  {
    family: "Georgia Pro Semibold Italic",
    path: "/fonts/georgia-pro/GeorgiaPro-SemiboldItalic.ttf",
    weight: "600",
    style: "italic",
  },
  {
    family: "Georgia Pro Bold",
    path: "/fonts/georgia-pro/GeorgiaPro-Bold.ttf",
    weight: "700",
    style: "normal",
  },
  {
    family: "Georgia Pro Bold Italic",
    path: "/fonts/georgia-pro/GeorgiaPro-BoldItalic.ttf",
    weight: "700",
    style: "italic",
  },
  {
    family: "Georgia Pro Black",
    path: "/fonts/georgia-pro/GeorgiaPro-Black.ttf",
    weight: "900",
    style: "normal",
  },
  {
    family: "Georgia Pro Black Italic",
    path: "/fonts/georgia-pro/GeorgiaPro-BlackItalic.ttf",
    weight: "900",
    style: "italic",
  },
  {
    family: "Georgia Pro Condensed",
    path: "/fonts/georgia-pro/GeorgiaPro-CondRegular.ttf",
    weight: "normal",
    style: "normal",
  },
  {
    family: "Georgia Pro Condensed Italic",
    path: "/fonts/georgia-pro/GeorgiaPro-CondItalic.ttf",
    weight: "normal",
    style: "italic",
  },
  {
    family: "Georgia Pro Condensed Light",
    path: "/fonts/georgia-pro/GeorgiaPro-CondLight.ttf",
    weight: "300",
    style: "normal",
  },
  {
    family: "Georgia Pro Condensed Light Italic",
    path: "/fonts/georgia-pro/GeorgiaPro-CondLightItalic.ttf",
    weight: "300",
    style: "italic",
  },
  {
    family: "Georgia Pro Condensed Bold",
    path: "/fonts/georgia-pro/GeorgiaPro-CondBold.ttf",
    weight: "700",
    style: "normal",
  },
  {
    family: "Georgia Pro Condensed Bold Italic",
    path: "/fonts/georgia-pro/GeorgiaPro-CondBoldItalic.ttf",
    weight: "700",
    style: "italic",
  },
  {
    family: "Georgia Pro Condensed Black",
    path: "/fonts/georgia-pro/GeorgiaPro-CondBlack.ttf",
    weight: "900",
    style: "normal",
  },
  {
    family: "Georgia Pro Condensed Black Italic",
    path: "/fonts/georgia-pro/GeorgiaPro-CondBlackItalic.ttf",
    weight: "900",
    style: "italic",
  },
  {
    family: "Georgia Pro Condensed Semibold",
    path: "/fonts/georgia-pro/GeorgiaPro-CondSemibold.ttf",
    weight: "600",
    style: "normal",
  },
  {
    family: "Georgia Pro Condensed Semibold Italic",
    path: "/fonts/georgia-pro/GeorgiaPro-CondSemiboldItalic.ttf",
    weight: "600",
    style: "italic",
  },

  // Lucida Sans Font Family
  {
    family: "Lucida Sans",
    path: "/fonts/lucida-sans/LSANS.TTF",
    weight: "normal",
    style: "normal",
  },
  {
    family: "Lucida Sans Italic",
    path: "/fonts/lucida-sans/LSANSI.TTF",
    weight: "normal",
    style: "italic",
  },
  {
    family: "Lucida Sans Demi",
    path: "/fonts/lucida-sans/LSANSD.TTF",
    weight: "600",
    style: "normal",
  },
  {
    family: "Lucida Sans Demi Italic",
    path: "/fonts/lucida-sans/LSANSDI.TTF",
    weight: "600",
    style: "italic",
  },
  {
    family: "Lucida Typewriter",
    path: "/fonts/lucida-sans/LTYPE.TTF",
    weight: "normal",
    style: "normal",
  },
  {
    family: "Lucida Typewriter Oblique",
    path: "/fonts/lucida-sans/LTYPEO.TTF",
    weight: "normal",
    style: "italic",
  },
  {
    family: "Lucida Typewriter Bold",
    path: "/fonts/lucida-sans/LTYPEB.TTF",
    weight: "700",
    style: "normal",
  },
  {
    family: "Lucida Typewriter Bold Oblique",
    path: "/fonts/lucida-sans/LTYPEBO.TTF",
    weight: "700",
    style: "italic",
  },
  {
    family: "Lucida Sans Unicode",
    path: "/fonts/lucida-sans/l_10646.ttf",
    weight: "normal",
    style: "normal",
  },

  // Montserrat Font Family
  {
    family: "Montserrat",
    path: "/fonts/Montserrat/Montserrat-VariableFont_wght.ttf",
    weight: "normal",
    style: "normal",
  },
  {
    family: "Montserrat Italic",
    path: "/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf",
    weight: "normal",
    style: "italic",
  },
  {
    family: "Montserrat Thin",
    path: "/fonts/Montserrat/static/Montserrat-Thin.ttf",
    weight: "100",
    style: "normal",
  },
  {
    family: "Montserrat Thin Italic",
    path: "/fonts/Montserrat/static/Montserrat-ThinItalic.ttf",
    weight: "100",
    style: "italic",
  },
  {
    family: "Montserrat ExtraLight",
    path: "/fonts/Montserrat/static/Montserrat-ExtraLight.ttf",
    weight: "200",
    style: "normal",
  },
  {
    family: "Montserrat ExtraLight Italic",
    path: "/fonts/Montserrat/static/Montserrat-ExtraLightItalic.ttf",
    weight: "200",
    style: "italic",
  },
  {
    family: "Montserrat Light",
    path: "/fonts/Montserrat/static/Montserrat-Light.ttf",
    weight: "300",
    style: "normal",
  },
  {
    family: "Montserrat Light Italic",
    path: "/fonts/Montserrat/static/Montserrat-LightItalic.ttf",
    weight: "300",
    style: "italic",
  },
  {
    family: "Montserrat Regular",
    path: "/fonts/Montserrat/static/Montserrat-Regular.ttf",
    weight: "normal",
    style: "normal",
  },
  {
    family: "Montserrat Italic",
    path: "/fonts/Montserrat/static/Montserrat-Italic.ttf",
    weight: "normal",
    style: "italic",
  },
  {
    family: "Montserrat Medium",
    path: "/fonts/Montserrat/static/Montserrat-Medium.ttf",
    weight: "500",
    style: "normal",
  },
  {
    family: "Montserrat Medium Italic",
    path: "/fonts/Montserrat/static/Montserrat-MediumItalic.ttf",
    weight: "500",
    style: "italic",
  },
  {
    family: "Montserrat SemiBold",
    path: "/fonts/Montserrat/static/Montserrat-SemiBold.ttf",
    weight: "600",
    style: "normal",
  },
  {
    family: "Montserrat SemiBold Italic",
    path: "/fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf",
    weight: "600",
    style: "italic",
  },
  {
    family: "Montserrat Bold",
    path: "/fonts/Montserrat/static/Montserrat-Bold.ttf",
    weight: "700",
    style: "normal",
  },
  {
    family: "Montserrat Bold Italic",
    path: "/fonts/Montserrat/static/Montserrat-BoldItalic.ttf",
    weight: "700",
    style: "italic",
  },
  {
    family: "Montserrat ExtraBold",
    path: "/fonts/Montserrat/static/Montserrat-ExtraBold.ttf",
    weight: "800",
    style: "normal",
  },
  {
    family: "Montserrat ExtraBold Italic",
    path: "/fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf",
    weight: "800",
    style: "italic",
  },
  {
    family: "Montserrat Black",
    path: "/fonts/Montserrat/static/Montserrat-Black.ttf",
    weight: "900",
    style: "normal",
  },
  {
    family: "Montserrat Black Italic",
    path: "/fonts/Montserrat/static/Montserrat-BlackItalic.ttf",
    weight: "900",
    style: "italic",
  },

  // Source Sans 3 Font Family
  {
    family: "Source Sans 3",
    path: "/fonts/Source_Sans_3/SourceSans3-VariableFont_wght.ttf",
    weight: "normal",
    style: "normal",
  },
  {
    family: "Source Sans 3 Italic",
    path: "/fonts/Source_Sans_3/SourceSans3-Italic-VariableFont_wght.ttf",
    weight: "normal",
    style: "italic",
  },
  {
    family: "Source Sans 3 ExtraLight",
    path: "/fonts/Source_Sans_3/static/SourceSans3-ExtraLight.ttf",
    weight: "200",
    style: "normal",
  },
  {
    family: "Source Sans 3 ExtraLight Italic",
    path: "/fonts/Source_Sans_3/static/SourceSans3-ExtraLightItalic.ttf",
    weight: "200",
    style: "italic",
  },
  {
    family: "Source Sans 3 Light",
    path: "/fonts/Source_Sans_3/static/SourceSans3-Light.ttf",
    weight: "300",
    style: "normal",
  },
  {
    family: "Source Sans 3 Light Italic",
    path: "/fonts/Source_Sans_3/static/SourceSans3-LightItalic.ttf",
    weight: "300",
    style: "italic",
  },
  {
    family: "Source Sans 3 Regular",
    path: "/fonts/Source_Sans_3/static/SourceSans3-Regular.ttf",
    weight: "normal",
    style: "normal",
  },
  {
    family: "Source Sans 3 Italic",
    path: "/fonts/Source_Sans_3/static/SourceSans3-Italic.ttf",
    weight: "normal",
    style: "italic",
  },
  {
    family: "Source Sans 3 Medium",
    path: "/fonts/Source_Sans_3/static/SourceSans3-Medium.ttf",
    weight: "500",
    style: "normal",
  },
  {
    family: "Source Sans 3 Medium Italic",
    path: "/fonts/Source_Sans_3/static/SourceSans3-MediumItalic.ttf",
    weight: "500",
    style: "italic",
  },
  {
    family: "Source Sans 3 SemiBold",
    path: "/fonts/Source_Sans_3/static/SourceSans3-SemiBold.ttf",
    weight: "600",
    style: "normal",
  },
  {
    family: "Source Sans 3 SemiBold Italic",
    path: "/fonts/Source_Sans_3/static/SourceSans3-SemiBoldItalic.ttf",
    weight: "600",
    style: "italic",
  },
  {
    family: "Source Sans 3 Bold",
    path: "/fonts/Source_Sans_3/static/SourceSans3-Bold.ttf",
    weight: "700",
    style: "normal",
  },
  {
    family: "Source Sans 3 Bold Italic",
    path: "/fonts/Source_Sans_3/static/SourceSans3-BoldItalic.ttf",
    weight: "700",
    style: "italic",
  },
  {
    family: "Source Sans 3 ExtraBold",
    path: "/fonts/Source_Sans_3/static/SourceSans3-ExtraBold.ttf",
    weight: "800",
    style: "normal",
  },
  {
    family: "Source Sans 3 ExtraBold Italic",
    path: "/fonts/Source_Sans_3/static/SourceSans3-ExtraBoldItalic.ttf",
    weight: "800",
    style: "italic",
  },
  {
    family: "Source Sans 3 Black",
    path: "/fonts/Source_Sans_3/static/SourceSans3-Black.ttf",
    weight: "900",
    style: "normal",
  },
  {
    family: "Source Sans 3 Black Italic",
    path: "/fonts/Source_Sans_3/static/SourceSans3-BlackItalic.ttf",
    weight: "900",
    style: "italic",
  },
];
