/**
 * The registration form a site starts with.
 *
 * These are seeded into `RegistrationField` so an owner can relabel, reorder,
 * make optional or disable any of them. The `system` ones may not be deleted,
 * only disabled — losing every identity field would leave a form that collects
 * nothing anybody can act on.
 *
 * Client-safe: no database import, so the CMS editor can show the same list.
 */
export const DEFAULT_REGISTRATION_FIELDS = [
  {
    key: "firstName",
    label: "First Name",
    type: "text",
    placeholder: "e.g. Ayesha",
    required: true,
    width: "half",
    bindTo: "firstName",
    system: true,
    maxLength: 100,
    displayOrder: 0,
  },
  {
    key: "lastName",
    label: "Last Name",
    type: "text",
    placeholder: "e.g. Khan",
    required: true,
    width: "half",
    bindTo: "lastName",
    system: true,
    maxLength: 100,
    displayOrder: 1,
  },
  {
    key: "email",
    label: "Email Address",
    type: "email",
    placeholder: "you@company.com",
    required: true,
    width: "half",
    bindTo: "email",
    system: true,
    maxLength: 200,
    displayOrder: 2,
  },
  {
    key: "phone",
    label: "Phone Number",
    type: "phone",
    placeholder: "+92 300 0000000",
    required: true,
    width: "half",
    bindTo: "phone",
    system: true,
    maxLength: 40,
    displayOrder: 3,
  },
  {
    key: "company",
    label: "Company / Organisation",
    type: "text",
    placeholder: "Where you work",
    required: false,
    width: "half",
    bindTo: "company",
    maxLength: 200,
    displayOrder: 4,
  },
  {
    key: "jobTitle",
    label: "Job Title",
    type: "text",
    placeholder: "Your role",
    required: false,
    width: "half",
    maxLength: 200,
    displayOrder: 5,
  },
  {
    key: "country",
    label: "Country",
    type: "country",
    required: true,
    width: "half",
    bindTo: "country",
    maxLength: 100,
    displayOrder: 6,
  },
  {
    key: "city",
    label: "City",
    type: "text",
    required: false,
    width: "half",
    maxLength: 100,
    displayOrder: 7,
  },
  {
    key: "address",
    label: "Address",
    type: "textarea",
    placeholder: "Street address",
    required: false,
    width: "full",
    maxLength: 500,
    displayOrder: 8,
  },
  {
    key: "additionalInformation",
    label: "Additional Information",
    type: "textarea",
    placeholder: "Anything we should know before the session?",
    helpText: "Accessibility requirements, prior qualifications, invoicing contact…",
    required: false,
    width: "full",
    maxLength: 2000,
    displayOrder: 9,
  },
];

/** Keys that ship with the form and may be disabled but not deleted. */
export const SYSTEM_FIELD_KEYS = DEFAULT_REGISTRATION_FIELDS.filter((f) => f.system).map(
  (f) => f.key,
);
